on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - name: Get RSS Feed
      uses: ./
      with:
        feed_url: https://hao.su/feed/
        count: 10
        readme_path: 'tests/readme.test.md'
    - name: Commit file changes
      run: |
          git config --global user.name 'wudongdefeng'
          git config --global user.email '615563901@qq.com'
          git add .
          git diff --quiet --cached || git commit -m "Update README"    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.USER_TOKEN }}
